author: Tim Studt
author_url: https://github.com/timstudt
module: MovieDB
module_version: 0.2.0
github_url: https://github.com/timstudt/movieDB
copyright: 'Copyright © 2019 Tim Studt. All rights reserved.'
readme: About.md

# swift_version: 5.0

theme: fullwidth

min_acl: internal

exclude:
  - generated/**
  - SourceryTemplates/**
  - fastlane/**
  - Pods/**
