sources:
  - MovieDBDataTests/Mocks/Automockable/
  - Domain/
  - Data/
templates:
  - SourceryTemplates
output:
  path: ./generated/
  link:
    project: MovieDB.xcodeproj
    target: MovieDBDataTests
    group: MovieDBDataTests/generated
