disabled_rules:
  - line_length
  - type_name

opt_in_rules:
  - anyobject_protocol
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - force_unwrapping
  - fatal_error_message
  - first_where
  - last_where
  - unused_import

included:
  - MovieDB
  - Data
  - Domain
  - MovieDBTests
  - MovieDBDataTests

reporter: "xcode"

function_body_length:
  warning: 15
  error: 20
file_length:
  warning: 100
  error: 150

# Rules severity

redundant_void_return:
  severity: error
