disabled_rules:
  - line_length
  - type_name

opt_in_rules:
  - empty_count
  - anyobject_protocol
  - force_unwrapping

included:
  - MovieDB
  - Data
  - Domain
  - MovieDBTests
  - MovieDBDataTests

function_body_length:
  warning: 50
