disabled_rules:
  - line_length
  - type_name

opt_in_rules:
  - anyobject_protocol
  - closure_body_length
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - file_types_order
  - force_unwrapping
  - fatal_error_message
  - first_where
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - private_action
  - static_operator
  - unused_import

included:
  - MovieDB
  - Data
  - Domain
  - MovieDBTests
  - MovieDBDataTests

# reporter: "xcode"

function_body_length:
  warning: 15
  error: 20
file_length:
  warning: 100
  error: 150

# Rules severity

redundant_void_return:
  severity: error
