language: swift
cache:
  - bundler
  - cocoapods
osx_image: xcode9.3
git:
  depth: 10
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - pod install --repo-update
  - gem install xcpretty-travis-formatter
  - xcrun simctl list

xcode_workspace: MovieDB.xcworkspace

# whitelist
branches:
  only:
    - master
